---
- hosts: localhost
  connection: local
  ignore_errors: true
  vars:
    become_for_package: "{{ ansible_distribution != 'MacOSX' }}"
  roles:
    - zsh
    - vim
    - directories
    - role: nvm
      nvm_profile: /home/spencer/.zshrc
