- name: install zsh
  ansible.builtin.package:
    name: zsh
    state: present
  become: "{{ become_for_package }}"
- name: oh-my-zsh
  shell: >
    ZSH=~/.oh-my-zsh sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  ignore_errors: true
- name: clone dotfiles
  ansible.builtin.git:
    clone: true
    repo: https://github.com/sdstolworthy/dotfiles.git
    dest: $HOME/.dotfiles
- name: link .zshrc
  ansible.builtin.file:
    path: $HOME/.zshrc
    src: $HOME/.dotfiles/zshrc
    state: link

