- name: install zsh
  ansible.builtin.package:
    name: zsh
    state: present
  become: "{{ become_for_package }}"
- name: oh-my-zsh
  shell: >
    ZSH=~/.oh-my-zsh sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  ignore_errors: true
- name: clone dotfiles
  ansible.builtin.git:
    clone: true
    repo: https://github.com/sdstolworthy/dotfiles.git
    dest: $HOME/.dotfiles
- name: link .my_profile
  ansible.builtin.file:
    path: $HOME/.my_profile
    src: $HOME/.dotfiles/profile
    state: link
- name: add profile source to zshrc
  ansible.builtin.lineinfile:
    path: $HOME/.zshrc
    line: source $HOME/.my_profile
    create: yes

