- name: install vim
  ansible.builtin.package:
    name: vim
    state: present
  become: true
- name: install vimconfig
  ansible.builtin.git:
    clone: true
    repo: https://github.com/sdstolworthy/vimconfig.git
    dest: $HOME/.vimconfig
- name: link .vimrc for nvim
  ansible.builtin.file:
    path: $HOME/.config/nvim/init.vim
    src: $HOME/.vimconfig/vimrc
    state: link
- name: link nvim lua folder 
  ansible.builtin.file:
    path: $HOME/.config/nvim/lua
    src: $HOME/.vimconfig/lua
    state: link
- name: link .vimrc for vim
  ansible.builtin.file:
    path: $HOME/.vimrc
    src: $HOME/.vimconfig/vimrc
    state: link
- name: install vim plug
  ansible.builtin.shell: |
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
- name: install vim plug - neovim
  ansible.builtin.shell: |
    sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
